### ISSUE TITLE
Vertical video cut off on Firefox

### ISSUE THREAD

**Issue by douglasrcjames** [twilio/twilio-video-app-react#178]
**Describe the bug**
Anytime the video is in a vertical (portrait) orientation, the video will get cut off, as if to fit just the width, but only on Firefox, Chrome seems to display the video as it should. 

**To Reproduce**
I have been displaying a portrait video with a mobile phone or a vertical monitor.

**Screenshots**
Sharing vertical monitor from Chrome and is being cut off on the Firefox browser (right) but not the Chrome browser (left).
![image](https://user-images.githubusercontent.com/22306305/80152071-e058c700-856f-11ea-873b-fb4084e52aa0.png)

**Environmet**
 - OS: Windows 10
 - Browser: Firefox 75
 - App Version: 0.1.0
 - SDK Version: 2.3.0
 - Node.js version: 12.3.1

**Comment by timmydoza** [comment]
Thanks for the issue @douglasrcjames!

I've confirmed that this is a problem in firefox. I'll take a look at it this week.

**Comment by jonra1993** [comment]
Hi @douglasrcjames how did you solve it? I am facing a issue where despite cellphone is in portrait mode, pc show image in landscape
![Screen Shot 2020-11-26 at 10 52 40 PM](https://user-images.githubusercontent.com/23468720/100409694-8b67bc80-303a-11eb-9b11-0d8bcb818bc3.png)
![Screen Shot 2020-11-26 at 10 53 00 PM](https://user-images.githubusercontent.com/23468720/100409695-8c98e980-303a-11eb-9b2c-5d7fc3710084.png)

**Comment by douglasrcjames** [comment]
Hmmm, is this only in Firefox? My issue was only happening on Firefox and I fixed it when I updated my code to their master branch awhile back. I haven't changed my codebase since to be updated to their master, so maybe the bug re-emerged?

**Comment by jonra1993** [comment]
Thanks @douglasrcjames this bug still persist I am using last master code. In my case it happens in Chrome
