### ISSUE TITLE
Unhandled Rejection (Error): The [LocalVideoTrack #2: b4ea0559-c915-4cd4-b278-cc046adc0c2a] was unpublished

### ISSUE THREAD

**Issue by jp9573** [twilio/twilio-video-app-react#218]
**Describe the bug**
During the video meeting switching on/off video sharing button quickly causes the following error.
`Unhandled Rejection (Error): The [LocalVideoTrack #2: b4ea0559-c915-4cd4-b278-cc046adc0c2a] was unpublished`

Here is the screenshot
![Screenshot 2020-05-27 at 6 21 41 PM](https://user-images.githubusercontent.com/16044885/83021518-be0f0900-a047-11ea-9c79-de7e25ad474c.png)

P.S. I'm running my code locally.

**Comment by ivansivaklepsi** [comment]
Same thing happened to me when trying to unpublish a track, when switching from one audio input to another.
![image](https://user-images.githubusercontent.com/47630266/83278389-d2800c80-a1d3-11ea-842e-9adad581cfe6.png)

**Comment by timmydoza** [comment]
Thanks for the issue @jp9573!

I can reproduce the issue that you have described. We have a ticket entered into our backlog to fix it. Thanks again!

**Comment by bsubotic** [comment]
Hi, any timeframe? Please. Thanks.

**Comment by fbrooks** [comment]
Is there any workaround for this so that the code doesn't blow chunks?

**Comment by ervijjusty** [comment]
+1 faced same problem

**Comment by timmydoza** [comment]
Sorry to hear that so many people are impacted by this issue. This issue will be prioritized and I'll have a PR for the fix up within a day.

**Comment by timmydoza** [comment]
I've merged a fix that should fix the issue. Please try it out and let me know how it works for all of you. Thanks!!

**Comment by liorshk** [comment]
Hey, we still have this error on iphones
![image](https://user-images.githubusercontent.com/7127502/88567099-ae0fa780-d03f-11ea-8196-be7f8052200c.png)

**Comment by kunsachdeva** [comment]
Still getting this error
