### ISSUE TITLE
Unable to build app - Subsequent property declarations must have the same type. Property 'setPriority' must be of type

### ISSUE THREAD

**Issue by diegopitt** [twilio/twilio-video-app-react#392]
Hello,

I am getting this error in types.ts:

![Untitled-1](https://user-images.githubusercontent.com/2548954/103162095-62089080-47a0-11eb-8dc1-6f1b7b5c89f0.png)

(method) LocalTrackPublication.setPriority(priority: Track.Priority): LocalTrackPublication
Subsequent property declarations must have the same type.  Property 'setPriority' must be of type '(priority: Priority) => LocalTrackPublication', but here has type '(priority: Priority) => void'.ts(2717)
index.d.ts(121, 5): 'setPriority' was also declared here.
Peek Problem (Alt+F8)
No quick fixes available

Package.json:
```
`{
  "name": "events",
  "version": "2.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@headlessui/react": "^0.2.0",
    "@types/twilio-video": "^2.7.0",
    "@types/d3-timer": "^2.0.0",
    "@types/react": "^16.9.19",
    "@types/react-dom": "^16.9.5",
    "typescript": "^4.1.3",
    "autoprefixer": "^10.0.4",
    "classnames": "^2.2.6",
    "d3-timer": "^2.0.0",
    "firebase": "^8.1.2",
    "firebase-admin": "^8.13.0",
    "firebase-functions": "^3.11.0",
    "isomorphic-unfetch": "^3.1.0",
    "js-cookie": "^2.2.1",
    "keen-slider": "^5.3.5",
    "lodash.isequal": "^4.5.0",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.32",
    "next": "latest",
    "next-cookies": "^2.0.3",
    "next-pwa": "^3.1.5",
    "nprogress": "^0.2.0",
    "postcss": "^8.1.14",
    "react": "^16.13.1",
    "react-dom": "^16.14.0",
    "tailwindcss": "^2.0.1",
    "twilio": "^3.54.1",
    "twilio-video": "^2.7.1"
  },
  "resolutions": {
    "@types/react": "^16.9.19"
  }
}`
```

**Comment by timmydoza** [comment]
Thanks for the issue @diegopitt!

I'm able to reproduce this issue when I install dependencies with `yarn` instead of `npm`. If you delete your `node_modules` directory and run `npm install`, do you still see the issue?

Yarn doesn't use the package versions as specified by `package-lock.json`. Instead, it installs the most recent version of packages (as dictated by package.json), and this sometimes introduces breaking changes.

If you still want to use `yarn` to install dependencies, first run the `yarn import` command. This will ensure that yarn installs the package versions that are specified in `package-lock.json`.

**Comment by diegopitt** [comment]
Thanks for the reply @timmydoza !

I deleted the `node_modules` and run `npm install` and the issue is still happening. Do you recommend any workaround as a fix? I commented the function bellow and I am able to build the app and deploy

```
  // interface LocalTrackPublication {
  //   setPriority: (priority: Track.Priority) => void;
  // }
```

**Comment by timmydoza** [comment]
That looks good to me @diegopitt!

I think the newer version of `@types/twilio-video` added the `setPrioirty` property to the `LocalTrackPublication` class, which is why there's a conflict here.  

Soon, the twilio-video SDK will ship with its own TypeScript definition file, and I'll update this `types.ts` file accordingly.

**Comment by douglasrcjames** [comment]
@timmydoza I tried @diegopitt 's solution to comment out LocalTrackPublication and that didn't allow me to build again. Any other fixes I should try to allow for my app to at least build again and have my video call components still work? Am I able to update the `types.ts` file on my own?

**Comment by douglasrcjames** [comment]
Investigated a bit more, fixed by visiting the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/twilio-video/index.d.ts) for the updated definitions and pulled them in changing these files:

**types.ts:**
```
  interface LocalTrackPublication {
    setPriority: (priority: Track.Priority) => LocalTrackPublication;
  }

  interface RemoteVideoTrack {
    isSwitchedOff: boolean;
    setPriority: (priority: Track.Priority) => RemoteVideoTrack;
  }
```
**VideoTrack.tsx:**
```
...
 return () => {
      track.detach(el);
      if (track.setPriority && priority) {
        // Passing `null` to setPriority will set the track's priority to that which it was published with.
        track.setPriority(priority); // TODO: this was updated from null to priority pass
      }
    };
...
```

**Comment by boyland** [comment]
Yes it seems this is still a problem: the types that twilio video exports don't permit `null` to be passed to `setPriority`.
